---
execution_type: server
repo_name: awesome-release/genai-stack
hostnames:
- api: api-release-docs-rag-${env_id}.${domain}
- chroma: chroma-release-docs-rag-${env_id}.${domain}
- front-end: front-end-release-docs-rag-${env_id}.${domain}
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
shared_volumes:
- name: models
  size: 60Gi
  type: persistent
parameters:
- name: llm
  type: string
  description: Can be any Ollama model tag, or gpt-4 or gpt-3.5 or claudev2
  default: llama3:8b
  optional: true
services:
- name: api
  image: awesome-release/genai-stack/release-api
  volumes: []
  command:
  - uvicorn
  - release_docs_api:app
  - "--host"
  - 0.0.0.0
  - "--port"
  - '8504'
  depends_on:
  - chroma
  readiness_probe:
    exec:
      command:
      - curl
      - "-f"
      - http://localhost:8504/
    period_seconds: 5
    timeout_seconds: 3
    failure_threshold: 5
    initial_delay_seconds: 0
  ports:
  - type: node_port
    target_port: '8504'
    port: '8504'
    loadbalancer: false
  envs:
  - key: CHROMA_HOST
    value: chroma
  - key: CHROMA_PORT
    value: 8000
  - key: LLM
    value: "${parameters.llm}"
  - key: EMBEDDING_MODEL
    value: sentence_transformer
  - key: OLLAMA_BASE_URL
    value: http://ollama:11434
  - key: LANGCHAIN_API_KEY
    value: "${LANGCHAIN_API_KEY}"
  - key: LANGCHAIN_PROJECT
    value: "${LANGCHAIN_PROJECT}"
  - key: LANGCHAIN_ENDPOINT
    value: https://api.smith.langchain.com
  - key: LANGCHAIN_TRACING_V2
    value: false
- name: chroma
  image: chromadb/chroma
  has_repo: false
  args:
  - "--workers"
  - '1'
  - "--host"
  - 0.0.0.0
  - "--port"
  - '8000'
  - "--proxy-headers"
  - "--log-config"
  - chromadb/log_config.yml
  - "--timeout-keep-alive"
  - '30'
  readiness_probe:
    exec:
      command:
      - curl
      - "-f"
      - http://localhost:8000/api/v1/heartbeat
    period_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
    initial_delay_seconds: 0
  ports:
  - type: node_port
    target_port: '8000'
    port: '8000'
    loadbalancer: false
- name: front-end
  image: awesome-release/genai-stack/front-end
  build:
    context: "."
    dockerfile: front-end.Dockerfile
  has_repo: true
  command:
  - npm
  - run
  - dev
  depends_on:
  - api
  ports:
  - type: node_port
    target_port: '8505'
    port: '8505'
    loadbalancer: false
  envs:
  - key: VITE_API_BASE_URL
    value: "${API_INGRESS_URL}"
- name: ollama
  image: ollama/ollama:latest
  has_repo: false
  memory:
    limits: 64Gi
    requests: 4Gi
  cpu:
    limits: 128
    requests: 2
  command:
  - ollama
  args:
  - serve
  ports:
  - type: node_port
    target_port: '11434'
    port: '11434'
    loadbalancer: false
  node_selector:
  - key: nvidia.com/gpu
    value: 'true'
  volumes:
  - name: shmem
    type: shmem
    size: 16Gi
    mount_path: "/dev/shm"
  - claim: models
    mount_path: "/root/.ollama"
jobs:
- name: pull-model
  image: releaseai/genai-stack-pull-model
  command:
  - bb
  - "-f"
  - pull_model.clj
  envs:
  - key: OLLAMA_BASE_URL
    value: http://ollama:11434
  - key: LLM
    value: "${parameters.llm}"
workflows:
- name: setup
  parallelize:
  - step: services-0
    tasks:
    - services.chroma
    - services.ollama
  - step: services-1
    tasks:
    - services.api
    - jobs.pull-model
  - step: services-2
    tasks:
    - services.front-end
- name: patch
  parallelize:
  - step: services-0
    tasks:
    - services.api
- name: teardown
  parallelize:
  - step: remove-environment
    tasks:
    - release.remove_environment


